export { default as About } from "./About"  
export { default as Contact } from "./Contact"
export { default as FeedCard } from "./FeedCard"    
export { default as LikeButton } from "./LikeButton"    
export { default as Loader } from "./Loader"